docs/config.js, docs/ja/README.md, docs/ja/cli.md, docs/ja/plugins.md
Finally, Japanese translation is here :tada:.
Though still need more professional advice, I think it would be much better than a 404 page :)
=> Japanese translation

docs/zh-Hant/README.md, docs/zh-Hant/cli.md, docs/zh-Hant/plugins.md
=> improve zh-Hant translation

README.md
Aha, it's [us](https://github.com/service-mocker/service-mocker) 🎉
=> Add service-mocker to users list

README.md
=> Add Koel into Projects Using Docute

src/components/HeaderIcons.vue, src/components/HeaderNav.vue, src/components/HomeHeader.vue
Fixes #71. Also fixes vertical align for icons when nav is empty.
=> Tooltip tweaks

docs/plugins.md
=> Emoji plugin.

README.md
Very pleased with docute, thought I'd share what I've come up with it!
=> Add vue-scrollto to "Projects Using Docute"

src/views/Landing.vue, src/views/Page.vue
Links：https://developers.google.com/web/updates/2015/03/introduction-to-fetch
完成本地测试
=> Support sending credentials with a fetch request

README.md
Add the document address of the open source project finger-mover to the Projects Using Docute
=> The finger-mover document address

docs/zh-Hans/README.md
`再` should be `在` in this sentence :
```
你不能再动态添加的页面里使用 script 标签
```
=> Wrong a word

README.md
=> Add link to Telegraf

docs/config.js, src/plugins/docsearch/index.js
Extract `algoliasearch` AppId to options.
=> docsearch-plugin: Extract appId to options

src/utils/marked.js
Close #128, Close #141
Signed-off-by: LI JIAHAO <lijiahao99131@gmail.com>
=> :bug: fix href in routerLinks on hash mode

src/components/MobileHeader.vue, src/components/PrevNextLinks.vue
Cache `this.navLinks`, specific problem can be viewed [#8728](https://github.com/vuejs/vue/issues/8728). Of course, users may not notice this improvement, but it will be better. 😀
=> tweak(perf): solve implicit performance problem

README.md
#175 Changed the wording of the repo's description.
=> #175 "Effortlessly documentation done right." -> "Effortless documentation, done right."

src/components/Header.vue, src/components/Sidebar.vue, src/components/SidebarToggle.vue, src/css/page-content.css, src/utils/markedRenderer.js, src/views/Home.vue
Fixes #215
Print view after applying changes in this PR:
=> feat: improve css in print view

website/docs/README.md, website/docs/guide/offline-support.md, website/docs/zh/README.md, website/docs/zh/guide/offline-support.md
Fix https://github.com/egoist/docute/issues/220
=> docs: fix doctype

package.json, src/PluginAPI.js, src/components/Header.vue, src/index.js, src/plugins/search/SearchBar.vue, src/plugins/search/index.js, src/utils/cssVariables.js, website/docs/plugin-api.md, website/docs/zh/plugin-api.md, yarn.lock
=> Implement search API, fix #217

src/plugins/dark-theme-toggler/DarkThemeToggler.vue, src/store.js, website/docs/options.md, website/docs/zh/options.md, website/index.js
=> feat: auto detect color preference

src/components/ImageZoom.vue, src/store.js, src/utils/marked.js, website/docs/builtin-components.md, website/docs/guide/deployment.md, website/docs/guide/plugin.md, website/docs/options.md, website/docs/zh/builtin-components.md, website/docs/zh/guide/deployment.md, website/docs/zh/guide/plugin.md, website/docs/zh/options.md
=> feat: add imageZoom option

src/components/Header.vue, src/components/PrevNextLinks.vue, src/plugins/search/SearchBar.vue, src/views/Home.vue
=> fix: tweak header and pager in print view
